url:
  login: "http://10.255.0.19/drcom/login"
  logout: "http://10.255.0.19/drcom/logout"  # ä¸çŸ¥é“ä¸ºå•¥è¦å†™ç™»å‡º

users:
  # å•ä¸ªè´¦æˆ·è®¾ç½®
  - user:
      userid: 201930****           # å­¦/å·¥å·
      password: *******            # å¯†ç 
      ISP: ç”µä¿¡                     # è¿è¥å•†ï¼Œå¯é€‰ï¼šæ•™èŒå·¥ã€ç”µä¿¡ã€è”é€šã€ç§»åŠ¨
      0MKKey: 123456               # ä¸çŸ¥é“æœ‰å•¥ç”¨ï¼Œä½†æ˜¯æœ‰ç”¨
  # å¤šè´¦å·è®¾ç½®ï¼Œå·²è§£é™¤è´¦å·ç™»é™†è®¾å¤‡æ•°é‡é™åˆ¶ï¼Œåº”ç”¨åœºæ™¯è¾ƒå°‘
#   - user:
#       userid:  # å­¦/å·¥å·
#       password: # å¯†ç 
#       ISP:  # è¿è¥å•†ï¼Œå¯é€‰ï¼šæ•™èŒå·¥ã€ç”µä¿¡ã€è”é€šã€ç§»åŠ¨

msg:
  go-cqhttp:
    # url æ¨é€åˆ°ä¸ªäººQQ: http://127.0.0.1:port/send_private_msg  ç¾¤ï¼šhttp://127.0.0.1:port/send_group_msg
    # token å¡«å†™åœ¨go-cqhttpæ–‡ä»¶è®¾ç½®çš„è®¿é—®å¯†é’¥
    # qq è¢«é€šçŸ¥çš„QQ
    # go-cqhttpç›¸å…³API https://docs.go-cqhttp.org/api
    url: "http://127.0.0.1:port/send_private_msg"
    token: *****************************
    qq: "2517421382"
  win:
    title: "è‡ªåŠ¨è¿æ¥ğŸ”—"  # Windows ç³»ç»Ÿé€šçŸ¥æ ‡é¢˜